name: Cypress Tests

on: push

jobs:

  cypress-run:
    runs-on: ubuntu-lastest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v2.2.7
        with:
          build: npm run build
          start: npx cypress run
